apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wisecow-tls
  namespace: default
spec:
  secretName: wisecow-tls-secret
  duration: 2160h     # 90 days
  renewBefore: 360h    # 15 days before expiration
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: wisecow.local
  dnsNames:
    - wisecow.local
